# Exercise 8: Dictionary Filtering
original_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
keys_to_keep = ['a', 'c', 'e']
filtered_dict = {key: value for key, value in original_dict.items() if key in keys_to_keep}
print("Filtered dictionary:", filtered_dict)

# `original_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}`:
#       Defines the original dictionary.
#
# `keys_to_keep = ['a', 'c', 'e']`:
#       Specifies the list of keys to keep from the original dictionary.
#
# `{key: value for key, value in original_dict.items() if key in keys_to_keep}`:
#       This is a dictionary comprehension that iterates over each key-value pair
#       (`key`, `value`) in the `original_dict`.
#       - For each pair, it checks if the key (`key`) is present in the `keys_to_keep`
#         list using the condition `if key in keys_to_keep`.
#       - If the key is in the list of keys to keep, it includes that key-value pair in
#         the new filtered dictionary.
#
# `filtered_dict = {...}`:
#       This line assigns the filtered dictionary generated by the dictionary
#       comprehension to the variable `filtered_dict`.
